### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by symroe** [mysociety/django-pipeline-csscompressor#1]
Hello :)

This is useful, but it would be even more useful if it were on PyPi, so it could be installed – as per the README – from pip.

I realise that I can use a `git+` URL to install it, but that's not possible when using `setuptools` (AFIK).

**Comment by tehfink** [comment]
Indeed! From the README:

``` bash
$ pip install django-pipeline-csscompressor
Collecting django-pipeline-csscompressor
  Could not find a version that satisfies the requirement django-pipeline-csscompressor (from versions: )
No matching distribution found for django-pipeline-csscompressor
```

**Comment by dracos** [comment]
Sorry this got missed! https://pypi.python.org/pypi/django-pipeline-csscompressor

**Comment by symroe** [comment]
FYI, I've stopped using this code as `libsass` has a `--compress` option that will compress the output. This works nicely with pipeline directly.

**Comment by dracos** [comment]
`--style compressed` presumably? :) Yes, we use libsass too; not sure if this is used anywhere... ah https://github.com/mysociety/researchsites_framework . And quite a few DC things, e.g. https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/requirements/base.txt :)

**Comment by symroe** [comment]
That'll be the one... Typing from memory :-)

**Comment by tehfink** [comment]
> FYI, I've stopped using this code as libsass has a --compress option that will compress the output. This works nicely with pipeline directly.

@symroe: could you give a quick example of your config setup with pipeline & libsass?

**Comment by symroe** [comment]
Sure, you're best off looking here I think:

https://github.com/DemocracyClub/dc_base_theme/blob/master/dc_theme/settings.py

You can't quite copy and paste from it, but it should be enough to get you started. Happy to answer questions, maybe over email to save Mathew's notifications :-)

**Comment by tehfink** [comment]
Thanks! I had assumed you were using this instead: https://github.com/sonic182/libsasscompiler

**Comment by symroe** [comment]
It looks like that project compresses the output when DEBUG is False https://github.com/sonic182/libsasscompiler/blob/d06acbd6de43fc5634ae0c8e7510cbe2c695adfc/libsasscompiler/__init__.py#L28

**Comment by tehfink** [comment]
Thanks, just ran across that as well. Explains why nothing was being compressed…
